name:                Log::Log4perl::Appender::Fluent
version:             0.01
abstract:            Log::Log4perl appender writing to Fluentd
license:             perl
distribution_type:   module
requires:
  base: 0
  Sys::Hostname:  0
  Fluent::Logger: 0
  Log::Log4perl::Appender: 0
author:
  - Stanislaw Klekot <cpan@jarowit.net>
